-- YOUTENT notifications + project payment-state fix
-- Run once in Supabase SQL Editor after the existing YOUTENT marketplace schema.

-- The project is created when a creator accepts a request, but work must not
-- start until the client has paid. Keep that state explicit.
ALTER TABLE public.projects
  DROP CONSTRAINT IF EXISTS projects_status_check;

UPDATE public.projects
SET status = 'pending_payment'
WHERE status = 'pending';

ALTER TABLE public.projects
  ADD CONSTRAINT projects_status_check
  CHECK (status IN ('pending_payment', 'active', 'completed', 'cancelled'));

-- ------------------------------------------------------------
-- Notifications
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  link text,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS notifications_user_created_idx
  ON public.notifications(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_user_unread_idx
  ON public.notifications(user_id, read_at)
  WHERE read_at IS NULL;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
CREATE POLICY "Users can read own notifications"
  ON public.notifications
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can mark own notifications read" ON public.notifications;
CREATE POLICY "Users can mark own notifications read"
  ON public.notifications
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No client-side INSERT policy: notifications are generated by trusted
-- SECURITY DEFINER trigger functions below.

CREATE OR REPLACE FUNCTION public.youtent_add_notification(
  p_user_id uuid,
  p_type text,
  p_title text,
  p_message text,
  p_link text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_user_id IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.notifications(user_id, type, title, message, link)
  VALUES (p_user_id, p_type, p_title, p_message, p_link);
END;
$$;

REVOKE ALL ON FUNCTION public.youtent_add_notification(uuid, text, text, text, text) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.youtent_project_request_notifications()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.youtent_add_notification(
      NEW.creator_id,
      'project_request',
      'New project request',
      COALESCE('You received a new project request: ' || NULLIF(NEW.project_title, ''), 'You received a new project request.'),
      '/requests'
    );
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
    IF NEW.status = 'accepted' THEN
      PERFORM public.youtent_add_notification(
        NEW.client_id,
        'request_status',
        'Your request was accepted',
        COALESCE('Your project request "' || NULLIF(NEW.project_title, '') || '" was accepted by the creator.', 'Your project request was accepted by the creator.'),
        '/my-requests'
      );
    ELSIF NEW.status = 'declined' THEN
      PERFORM public.youtent_add_notification(
        NEW.client_id,
        'request_status',
        'Your request was rejected',
        COALESCE('Your project request "' || NULLIF(NEW.project_title, '') || '" was rejected by the creator.', 'Your project request was rejected by the creator.'),
        '/my-requests'
      );
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS youtent_project_request_notifications_insert ON public.project_requests;
CREATE TRIGGER youtent_project_request_notifications_insert
AFTER INSERT ON public.project_requests
FOR EACH ROW
EXECUTE FUNCTION public.youtent_project_request_notifications();

DROP TRIGGER IF EXISTS youtent_project_request_notifications_update ON public.project_requests;
CREATE TRIGGER youtent_project_request_notifications_update
AFTER UPDATE OF status ON public.project_requests
FOR EACH ROW
EXECUTE FUNCTION public.youtent_project_request_notifications();

-- Direct creator messages are stored with creator_id, so the creator is the
-- recipient whenever a client sends a message to them.
CREATE OR REPLACE FUNCTION public.youtent_creator_message_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NEW.sender_id IS DISTINCT FROM NEW.creator_id THEN
    PERFORM public.youtent_add_notification(
      NEW.creator_id,
      'message',
      'New message',
      'You received a new message from a client.',
      '/dashboard/messages'
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS youtent_creator_message_notification_insert ON public.creator_messages;
CREATE TRIGGER youtent_creator_message_notification_insert
AFTER INSERT ON public.creator_messages
FOR EACH ROW
EXECUTE FUNCTION public.youtent_creator_message_notification();

